### ISSUE TITLE
menu-icon has div but is wrapped in span

### ISSUE THREAD

**Issue by danielfdickinson** [bowman2001/perplex#132]
There is another set of issues from around the same time. In https://github.com/bowman2001/perplex/commit/576720921da810090570208078fa71392c74c9e8
you modified a `blog/nav/pages` and `doc/nav/pages` to use span instead of div around `menu-icon` (sections like:

https://github.com/bowman2001/perplex/blob/2de96ee032c4e58ad2ad248b6b1280f4d279b21a/layouts/partials/doc/nav/pages.html#L20-L22

Either `menu-icon` needs to use `span` or these need to get changed back to `div`. I'm not sure why you made the change, but I've decided to try make the menu-icon `div`s `span`s instead.

_Originally posted by @danielfdickinson in https://github.com/bowman2001/perplex/issues/130#issuecomment-1850078955_

**Comment by bowman2001** [comment]
Thanks for the bug report. Because the CSS for the theme is pre-generated, I need to fix it myself.

**Comment by danielfdickinson** [comment]
Makes sense. I suspected that might the case, but I thought I'd give you the option.
