### ISSUE TITLE
Wrong featured image for posts with no defined featured image

### ISSUE THREAD

**Issue by danielfdickinson** [bowman2001/perplex#139]
So, I have an image which I have defined in /_index.md as a featured image, so it is my understanding that this image ought to be the image used whenever there is no featured image defined for a post.

(That image is: 

![image](https://github.com/bowman2001/perplex/assets/20735818/fc2fd980-f53e-4d61-8917-fa78030478b2)

However, as you can see below some posts (e.g. The "Everything's Fine Mask", November, Foolishness, and Thoughts on a new room) are using an image from a previous post (My bowels, like water).

I show the blog list page below.

![image](https://github.com/bowman2001/perplex/assets/20735818/d2b325d2-b13a-4705-98dd-e5f76622e46c)

I suspect that it is using the featured image due to same tags (poetry) but that is a guess.

The repository for the not yet published site is: <https://gitlab.com/danielfdickinson/pp-princesandmadmen>

**Comment by bowman2001** [comment]
The theme partial for the resource fallback is probably confusing. It works as expected, but it’s not intuitive as the default, and I consider this to be a design flaw. I need to think a bit about this, but I will probably change it to the behavior you did expect:
In case there is no featured image for a single page, try to take the one from the containing branch bundle.
