### ISSUE TITLE
colors from screen.css override color-default.css and color.css

### ISSUE THREAD

**Issue by danielfdickinson** [bowman2001/perplex#147]
Because https://github.com/bowman2001/perplex/blob/d07aa19ec2151054ede20b853bdae5e17cf87756/assets/css/screen.css#L43 and below still has the color scheme, and because

https://github.com/bowman2001/perplex/blob/d07aa19ec2151054ede20b853bdae5e17cf87756/layouts/partials/head/css.html#L8

adds the `color-default.css` or `color.css` _before_ `screen.css`, the CSS properties in `screen.css` override the color schemes.

I believe the solution is to remove the default color scheme from `screen.css` since it is now in `css-default.css` anyway.

I have figured out the PostCSS `screen.css` | `screen.post.css` magic, so I could create a PR if you wish.

**Comment by bowman2001** [comment]
You’re right, I just forgot to remove it. I will handle this bug like all CSS related stuff myself. But I will offer a mechanism to include custom CSS as you proposed.

**Comment by danielfdickinson** [comment]
I suspected you head meant to remove it. I appreciated your wanting to maintain the CSS yourself, and will endeavor to remember that. And thank you for working on a custom CSS mechanism. I've got something that works for me, for now, but I look forward to seeing what you build.
