### ISSUE TITLE
Links to taxonomy terms display things like quotes (') as HTML entities (e.g. \&rsquo;)

### ISSUE THREAD

**Issue by danielfdickinson** [bowman2001/perplex#156]
For example on this page:

https://www.princesandmadmen.ca/authors/

For the tags taxonomy, one sees:

[Daniel\&rsquo;s Archives](https://www.princesandmadmen.ca/tags/archives/)(9)‍ •

**Comment by bowman2001** [comment]
Thanks. There is an obsolete `.Renderstring` in the template. Taxonomy terms should always be strings and don't need any rendering.
