### ISSUE TITLE
How to re-use  your Kroki functionality to render diagrams without perplex

### ISSUE THREAD

**Issue by ezzle** [bowman2001/perplex#163]
Hi

I am Looking for a way to render diagram with Kroki in my Hugo generated site.

Perplex theme provides the functionality. For now, I am using another theme.

Can I re-use the functionality with another theme ? How ?

In addition, It will be optimal if you can submit a proposal to integrate natively this functionality in Hugo. 

Thank you for the help.

Best regards,

Tshitshi

**Comment by bowman2001** [comment]
Hi Tshitshi,
The code is here and you can find a link to the original template and an extensive article in my docs.
You should be able to re-use the functionality with all this information. 

Hugo provides only a few and very essential internal templates. This is probably never one of them.
