### ISSUE TITLE
Footer offset / not centered on authors page

### ISSUE THREAD

**Issue by Kariton** [bowman2001/perplex#165]
On the authors page the footer is not centered.

https://perplex.desider.at/authors/georg-makowski/

maybe intended but this somehow bothers me. :D

**Comment by bowman2001** [comment]
I see your point, but this is a matter of taste. When I look at a completely populated author page like my own at https://perplex.desider.at/authors/georg-makowski/ the alignment of the footer is in accordance with the cards above it.
